#!/bin/sh

### BEGIN INIT INFO
# Provides:          ipad-managerd
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: IPAd Manager daemon
### END INIT INFO

DAEMON=/usr/local/bin/ipad-managerd
CONFIG=/etc/ipad-manager/config.json
PIDFILE=/run/ipad-manager/ipad-managerd.pid

case "$1" in
    start)
        mkdir -p /run/ipad-manager /var/lib/ipad-manager /var/log/ipad-manager
        start-stop-daemon --start --background --make-pidfile --pidfile "$PIDFILE" --exec "$DAEMON" -- --config "$CONFIG"
        ;;
    stop)
        start-stop-daemon --stop --pidfile "$PIDFILE" --retry 5
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    status)
        start-stop-daemon --status --pidfile "$PIDFILE"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 2
        ;;
esac

exit $?
