export const slides = [
  { type: "cover", section: "概览", audiences: "管理｜客户｜研发", title: "IPAd SDK 与 IPAd Manager", subtitle: "功能能力、接口调用、分层架构、兼容性与一键部署全景说明", kicker: "TECHNICAL BUSINESS REVIEW · 2026", note: "基于当前仓库代码与文档核验" },
  { type: "agenda", section: "导航", audiences: "管理｜客户｜研发", title: "一套母版，支持三类受众按需裁剪", items: ["01  产品定位与端到端全景", "02  IPAd SDK 能力与公开接口", "03  IPAd Manager 分层实现", "04  兼容性、部署与使用", "05  当前状态、风险与路线图", "06  API、配置与构建附录"] },
  { type: "cards", section: "执行摘要", audiences: "管理｜客户｜研发", title: "IPAd 把 eUICC 底层协议能力组织成可集成、可操作的桌面管理链路", intro: "当前仓库已形成 SDK + GTK Manager 的基本产品形态，但“接口存在、Wrapper 已封装、GUI 已接入”并非同一成熟度。", cards: [
    ["SDK 核心", "覆盖 eUICC 信息、Profile 查询、EIM 配置、Fallback、应急 Profile、通知与多协议连接。"],
    ["Manager 价值", "通过 GTK GUI、业务逻辑和 Wrapper 降低直接调用 ES10/APDU/AT 的集成门槛。"],
    ["当前边界", "Profile 下载/启停/删除仍为占位；部分通信和通知 Wrapper 尚未形成完整 GUI 参数链路。"],
    ["部署形态", "面向 Linux/Ubuntu 构建，可在 Windows + WSL 的 Ubuntu 发行版中完成依赖安装、编译和运行。"] ] },
  { type: "flow", section: "产品全景", audiences: "管理｜客户｜研发", title: "外部应用通过 Manager 或 SDK 两条路径进入同一 eUICC 能力栈", intro: "上层入口不同，最终都收敛到 SDK Core、ES10/TLV 和硬件/网络适配层。", steps: ["操作员 / 外部系统", "IPAd Manager GUI\n或直接 C API", "SDK Wrapper / ipa_*", "SDK Core + ES10/TLV", "AT / APDU / 网络", "eUICC · eIM · SM-DP+"] },
  { type: "cards", section: "产品全景", audiences: "管理｜客户", title: "六类场景构成当前产品能力边界", intro: "能力覆盖“查询—控制—通信—通知—运维”，但并非所有入口都已达到同等可用程度。", cards: [
    ["设备识别", "读取 EID、EuiccInfo1/2、证书与 PKID。"], ["Profile 盘点", "获取 Profile 列表、状态与原始 TLV。"],
    ["策略控制", "Fallback、Return、Rollback Result、应急 Profile。"], ["通知运维", "初始化、全部投递、单条投递与删除。"],
    ["eIM 通信", "MQTT、LwM2M、HTTP 服务连接和停止。"], ["本地配置", "默认 SM-DP+、初始 eIM、内存重置、即时启用配置。"] ] },
  { type: "section", section: "SDK", audiences: "客户｜研发", title: "第一部分｜IPAd SDK 能力与接口", subtitle: "从公开 API、生命周期和调用链理解外部集成方式" },
  { type: "cards", section: "SDK 能力地图", audiences: "客户｜研发", title: "SDK 能力可归纳为八个稳定的功能域", intro: "能力域按调用目的组织；具体可用性还要结合构建选项、驱动与上层接入状态判断。", cards: [
    ["生命周期", "初始化、反初始化、事件回调、任务回调。"], ["eUICC 信息", "EID、EuiccInfo1/2、证书/PKID。"],
    ["Profile 信息", "Profile 列表、状态回调、原始 TLV。"], ["EIM 配置", "读取与添加 eIM、服务器地址配置。"],
    ["恢复机制", "Fallback、Return、Rollback Result。"], ["应急能力", "启用/禁用应急 Profile。"],
    ["通知", "列举、投递、单条处理、删除。"], ["网络服务", "MQTT、LwM2M、HTTP。"] ] },
  { type: "flow", section: "SDK 生命周期", audiences: "研发", title: "正确的外部调用从配置、回调和初始化状态开始", intro: "所有业务 API 都应在初始化成功后调用，并在退出前停止服务、释放返回对象、完成反初始化。", steps: ["准备 ipa_config_t", "注册事件/任务回调", "ipa_init_library", "调用 ipa__* / ipa_local__*", "释放 API 返回资源", "停止服务", "ipa_deinit_library"] },
  { type: "table", section: "SDK 生命周期", audiences: "研发", title: "初始化契约同时决定设备通道、日志与网络能力", intro: "实际字段以 ipa_config_t 和相关 typedef 为准；Manager 目前只应用了其中一部分配置链路。", columns: ["关注项", "外部调用责任", "当前说明"], rows: [
    ["配置生命周期", "配置对象在初始化期间保持有效", "避免把短生命周期栈对象交给后台线程"],
    ["事件回调", "处理初始化、服务及错误事件", "Manager 当前 event_cb 为空实现"],
    ["任务回调", "可接管线程创建/结束", "示例应用提供注册方式"],
    ["初始化结果", "以真实完成事件或返回结果判定", "Wrapper 当前较早设置 initialized"],
    ["反初始化", "先停止服务，再释放 SDK", "避免后台任务访问失效配置"] ] },
  { type: "cards", section: "eUICC 查询", audiences: "客户｜研发", title: "信息查询接口覆盖身份、能力、证书、Profile 与 EIM 配置", intro: "查询接口通常返回结构化数据；调用方需要遵循对应 free API 或所有权约定。", cards: [
    ["ipa__get_eid_cstring", "将 eUICC EID 写入调用方缓冲区。"], ["ipa__get_euicc_info_1", "读取 euiccInfo1，并用专用 free 释放。"],
    ["ipa__get_euicc_info_2", "读取 euiccInfo2，并用专用 free 释放。"], ["ipa__get_certs", "获取证书与 PKID 列表。"],
    ["ipa__get_all_profiles_info", "返回 Profile 数组、数量及可选原始 TLV。"], ["ipa__get_eim_configuration", "读取当前 eIM 配置及响应 TLV。"] ] },
  { type: "flow", section: "SDK 调用链", audiences: "研发", title: "一次典型查询会穿过公开 API、ES10、APDU/AT 和 TLV 解析", intro: "大多数同步查询遵循相似骨架，差异集中在 ES10 命令、TLV 生成与结果解析。", steps: ["公开 ipa__* API", "es10__init", "生成 ES10/TLV 请求", "APDU 通过 AT 驱动发送", "读取 eUICC 响应", "TLV 解析为结构体", "es10__deinit + 返回 ErrCode"] },
  { type: "cards", section: "Profile 与策略", audiences: "客户｜研发", title: "查询与恢复控制已具备底层入口，Profile 生命周期操作仍需补齐", intro: "必须区分 SDK 已存在能力与 Manager Wrapper 的占位接口。", cards: [
    ["Profile 列表", "已存在 SDK 查询入口，GUI 可展示列表信息。"], ["状态回调", "SDK 可注册 Profile 状态变化回调。"],
    ["Fallback", "执行 fallback mechanism，Manager GUI 已有入口。"], ["Return", "从 fallback 返回，Manager GUI 已有入口。"],
    ["Rollback Result", "向 eUICC 报告回滚结果，SDK 示例存在。"], ["下载/启停/删除", "Manager Wrapper 当前返回 eNotImpl，不能视为可用。"] ] },
  { type: "cards", section: "通知与应急", audiences: "客户｜研发", title: "通知和应急 Profile 已形成多级能力，但 GUI 参数化程度不同", intro: "全部通知与全部删除适合无参数按钮；单条操作需要序列号输入与结果展示。", cards: [
    ["初始化通知组", "读取并维护通知列表。"], ["投递全部通知", "SDK 与 Manager GUI 均有入口。"],
    ["投递单条通知", "Wrapper 已封装，GUI 尚需序列号输入链路。"], ["删除单条通知", "Wrapper 已封装，GUI 尚需参数链路。"],
    ["删除全部通知", "SDK 与 Manager GUI 均有入口。"], ["应急 Profile", "启用/禁用接口已接入 GUI。"] ] },
  { type: "table", section: "网络服务", audiences: "客户｜研发", title: "eIM/eSIPa 通信可按 MQTT、LwM2M、HTTP 三种协议构建", intro: "协议能力由 CMake 特性、第三方依赖和运行配置共同决定。", columns: ["协议", "主要用途/特性", "当前接入状态"], rows: [
    ["MQTT", "Broker、主题、QoS、认证、TLS；底层含重连逻辑", "Wrapper 已封装，GUI 配置链路不完整"],
    ["LwM2M", "Client/Bootstrap、UDP/DTLS、对象模型", "Wrapper 已封装，GUI 配置链路不完整"],
    ["HTTP", "URL、请求体、超时、响应读取", "Wrapper 已封装，GUI 配置链路不完整"],
    ["Stop service", "停止 HTTP、MQTT、LwM2M 后台服务", "GUI 已有统一停止入口"] ] },
  { type: "table", section: "接口契约", audiences: "研发", title: "ErrCode 是统一失败面，但调用方仍需保留上下文和日志", intro: "错误码负责分类，诊断还依赖参数、底层日志、APDU/网络响应和运行阶段。", columns: ["类别", "典型含义", "调用方建议"], rows: [
    ["eOk", "调用成功", "继续处理返回数据并按约定释放"], ["eFail", "通用失败", "结合日志定位 ES10、设备或网络阶段"],
    ["eInvalidParam", "参数或缓冲区无效", "调用前校验指针、长度和字符串"], ["eNotImpl", "当前入口未实现", "禁止在产品流程中视为可降级成功"],
    ["资源/通信类", "内存、APDU、连接或解析失败", "记录原始响应与重试边界"] ] },
  { type: "flow", section: "外部集成", audiences: "客户｜研发", title: "直接集成 SDK 的最小闭环包含七个步骤", intro: "建议先用只读查询验证设备链路，再逐步启用通知、网络和控制类能力。", steps: ["链接 SDK 与依赖", "包含 ipa.h/typedefs", "构造配置", "注册回调", "初始化 SDK", "调用并释放结果", "停止服务并反初始化"] },
  { type: "table", section: "外部集成", audiences: "研发", title: "接口使用中最容易遗漏的是缓冲区、所有权与后台任务生命周期", intro: "这些约束应在上层 Wrapper 中统一，而不是散落到每个按钮回调。", columns: ["约束", "风险", "推荐封装"], rows: [
    ["字符串缓冲区", "长度不足或未终止", "统一固定上限与返回长度检查"],
    ["结构化返回值", "忘记专用 free", "Wrapper 转换为自有 DTO 后立即释放 SDK 对象"],
    ["原始 TLV", "所有权不清晰", "接口文档标明分配者和释放者"],
    ["异步服务配置", "栈对象在线程中失效", "复制到长生命周期上下文"],
    ["回调线程", "直接更新 GTK 导致线程问题", "通过主循环投递 UI 更新"] ] },
  { type: "section", section: "Manager", audiences: "管理｜客户｜研发", title: "第二部分｜IPAd Manager 分层实现", subtitle: "从 GTK 界面到 SDK Core 的职责边界与调用路径" },
  { type: "layers", section: "Manager 架构", audiences: "管理｜客户｜研发", title: "Manager 通过五层结构隔离界面、业务语义与底层协议", layers: [
    ["表现层", "GTK GUI · 窗口 · 菜单 · 日志区 · 参数输入"],
    ["业务层", "API 定义 · 命令构造 · 结果格式化 · 状态展示"],
    ["适配层", "ipad_wrapper_* · 错误映射 · SDK 生命周期"],
    ["SDK 核心", "ipa_* · RSP/EIM · ES10 · TLV · 通知/策略"],
    ["基础设施", "AT/APDU · MQTT/LwM2M/HTTP · eUICC · eIM · SM-DP+"] ] },
  { type: "table", section: "Manager 架构", audiences: "研发", title: "每一层都应只承担一种变化来源", intro: "当前结构已经具备分层骨架，但部分配置、线程和状态仍跨层泄漏。", columns: ["层/模块", "主要文件", "职责"], rows: [
    ["启动与生命周期", "src/main.c", "初始化 GTK、Wrapper、窗口与退出清理"],
    ["GUI", "src/gui/gui_main.c", "控件、动作分发、日志与结果展示"],
    ["API 元数据", "include/app_api_definitions.h", "名称、分类、描述和可见操作"],
    ["业务逻辑", "src/business_logic/command_builder.c", "构造命令和错误文本"],
    ["SDK Wrapper", "src/sdk_wrapper/ipad_wrapper.c", "把 GUI 语义映射到 SDK"],
    ["配置工具", "src/utils/config_manager.c", "默认值、JSON 解析、校验与保存"] ] },
  { type: "flow", section: "Manager 调用链", audiences: "研发", title: "一次按钮操作从字符串分发开始，最终映射到 ipa_* API", intro: "当前 GUI 使用 API 名称字符串进行分支判断；可工作，但扩展性和类型安全有限。", steps: ["用户点击功能", "读取 API 定义项", "gui_main 字符串比较", "收集/补齐参数", "ipad_wrapper_*", "ipa__* / ipa_local__*", "格式化结果与日志"] },
  { type: "table", section: "GUI 接入", audiences: "客户｜研发", title: "GUI 当前直接接通的能力集中在查询、恢复、批量通知和应急操作", intro: "下表反映当前代码路径，不以发布说明中的完成标记代替验证。", columns: ["功能", "GUI", "Wrapper/SDK", "状态"], rows: [
    ["EID / EuiccInfo1/2", "有入口", "已调用 SDK", "已实现并接入"],
    ["证书 / Profile / EIM 配置查询", "有入口", "已调用 SDK", "已实现并接入"],
    ["Fallback / Return", "有入口", "已调用 SDK", "已实现并接入"],
    ["全部通知 / 删除全部", "有入口", "已调用 SDK", "已实现并接入"],
    ["应急 Profile 启停", "有入口", "已调用 SDK", "已实现并接入"],
    ["停止 EIM 服务", "有入口", "统一停止", "已实现并接入"] ] },
  { type: "table", section: "GUI 接入", audiences: "研发", title: "部分 Wrapper 已存在，但缺少 GUI 参数、状态或结果闭环", intro: "这类能力应标记为“接入不完整”，不宜与可交付功能混为一谈。", columns: ["能力", "底层/Wrapper", "缺口", "状态"], rows: [
    ["MQTT 连接", "存在", "Broker、认证、TLS 配置未完整贯通", "接入不完整"],
    ["LwM2M 连接", "存在", "端点、Bootstrap、DTLS 参数未完整贯通", "接入不完整"],
    ["HTTP 连接", "存在", "URL、超时、证书参数未完整贯通", "接入不完整"],
    ["单条通知投递", "存在", "序列号输入与结果闭环", "接入不完整"],
    ["单条通知删除", "存在", "序列号输入与刷新闭环", "接入不完整"],
    ["配置文件应用", "解析存在", "启动时查找与 SDK/UI 应用链", "接入不完整"] ] },
  { type: "cards", section: "功能模板", audiences: "客户｜研发", title: "Manager 的功能模板可按“查询、动作、会话、配置”四种交互模型组织", intro: "统一模板能够减少每个 API 单独写 UI 和错误处理的成本。", cards: [
    ["查询模板", "无参数或少量参数 → 调用 → 结构化结果表格 → 可复制日志。"],
    ["动作模板", "风险提示 → 确认 → 执行 → 状态刷新；适合 Fallback/应急操作。"],
    ["会话模板", "连接参数 → 启动后台服务 → 状态/重连 → 停止。"],
    ["配置模板", "读取 JSON → 默认值 → 校验 → 应用 → 保存；敏感项单独处理。"] ] },
  { type: "flow", section: "启动与关闭", audiences: "研发", title: "主程序启动链路已具备，但初始化完成状态应更加严格", intro: "当前 Wrapper 在 ipa_init_library 返回后较早标记 initialized；若 SDK 内部仍异步初始化，可能产生竞态。", steps: ["加载配置路径", "创建 GTK 主窗口", "ipad_wrapper_init", "ipa_init_library", "注册任务回调", "进入 GTK 主循环", "退出时 deinit"] },
  { type: "table", section: "配置与日志", audiences: "客户｜研发", title: "配置组件已具备解析基础，真正的生产链路还需完成“查找—应用—验证”", intro: "示例配置覆盖设备、日志和网络协议，但证书路径与运行对象的绑定仍需核验。", columns: ["配置域", "已有能力", "待完善"], rows: [
    ["文件加载", "JSON 解析、默认值、基础校验", "启动时多路径查找与错误提示"],
    ["设备通道", "配置结构存在", "串口/驱动选择与可用性探测"],
    ["MQTT/LwM2M/HTTP", "默认项和解析存在", "完整传入 Wrapper 与后台服务上下文"],
    ["TLS/DTLS", "证书路径字段/说明存在", "验证、加载与失败反馈闭环"],
    ["日志", "GUI 日志与 SDK 日志", "级别、脱敏、轮转和导出"] ] },
  { type: "table", section: "线程与资源", audiences: "研发", title: "线程和资源所有权是当前最值得优先治理的横切问题", intro: "问题不一定立即触发，但会在重连、退出、反复查询和错误路径中放大。", columns: ["问题", "现状证据", "影响", "建议"], rows: [
    ["异步初始化状态", "Wrapper 提前置 initialized", "业务调用过早", "以完成事件驱动状态机"],
    ["空事件回调", "event_cb 无处理", "丢失服务/错误状态", "映射到统一事件总线"],
    ["栈配置传线程", "服务配置为局部对象", "悬空引用风险", "深拷贝到会话上下文"],
    ["Profile 释放", "free_profiles 为空", "重复查询泄漏", "明确 DTO 与释放契约"],
    ["字符串分发", "strcmp 选择动作", "重构易出错", "函数表/命令对象"] ] },
  { type: "section", section: "部署", audiences: "客户｜研发", title: "第三部分｜兼容性、一键部署与使用", subtitle: "明确运行环境、构建选项、部署边界与操作步骤" },
  { type: "table", section: "兼容性", audiences: "客户｜研发", title: "当前主路径是 Linux/Ubuntu + GTK + AT，其他组合取决于构建与验证", intro: "“代码可编译”不等于“硬件与服务器组合已验证”，兼容性应分层表述。", columns: ["维度", "主路径", "可选/条件", "说明"], rows: [
    ["操作系统", "Ubuntu/Linux", "Windows 通过 WSL", "GUI 显示需 WSLg/X Server"],
    ["规范", "SGP.32 默认", "SGP.22 可编译选择", "两者不可同时定义"],
    ["eUICC 驱动", "AT", "PCSC 构建项", "当前真实主路径为 AT"],
    ["网络", "HTTP/MQTT/LwM2M 可启用", "依赖库与服务端", "按 CMake 开关裁剪"],
    ["UI", "GTK 3", "无界面 SDK 应用", "SDK 可脱离 Manager 集成"] ] },
  { type: "table", section: "构建选项", audiences: "研发", title: "CMake 特性开关决定最终二进制的协议与驱动组合", intro: "部署包应记录构建参数，避免运行期才发现能力未编译。", columns: ["开关/特性", "默认/现状", "影响"], rows: [
    ["SGP32", "默认开启", "选择 SGP.32 ES10 与 TLV 定义"],
    ["SGP22", "与 SGP32 互斥", "选择另一套规范编译路径"],
    ["ENABLE_MQTT", "开启", "链接 MQTT 客户端实现"],
    ["ENABLE_LWM2M", "开启", "包含 Wakaama/LwM2M 实现"],
    ["ENABLE_HTTP", "开启", "链接 libcurl HTTP 实现"],
    ["PCSC", "默认关闭", "启用 PC/SC 智能卡通道"] ] },
  { type: "flow", section: "一键部署", audiences: "客户｜研发", title: "quickstart.sh 将环境检查、依赖、构建与启动串成一条路径", intro: "生产环境建议把系统依赖安装与应用构建拆成可审计的两阶段。", steps: ["确认 Ubuntu/WSL", "安装编译与 GTK 依赖", "build_sdk.sh", "构建 SDK 产物", "build_all.sh", "构建 Manager", "写入配置并启动"] },
  { type: "table", section: "一键部署", audiences: "研发", title: "三个脚本承担不同粒度的自动化职责", intro: "使用前应检查执行权限、网络代理、apt 源和硬件访问权限。", columns: ["脚本", "用途", "适用场景"], rows: [
    ["quickstart.sh", "依赖准备 + 构建 + 快速启动", "首次体验或开发环境初始化"],
    ["build_sdk.sh", "单独配置和构建 ipa_sdk_pc", "SDK 开发、CI 或独立集成"],
    ["build_all.sh", "构建 SDK 与 ipad_host_app", "完整 Manager 交付"],
    ["手工 CMake", "显式指定特性与目录", "生产、交叉编译、问题定位"] ] },
  { type: "flow", section: "使用说明", audiences: "客户｜研发", title: "建议先验证只读链路，再启用控制和后台通信", intro: "从低风险到高风险逐步验证，可更快区分设备、SDK、GUI 和服务器问题。", steps: ["启动并检查日志", "读取 EID", "读取 EuiccInfo1/2", "查看证书与 Profile", "验证 EIM 配置", "测试通知/应急", "配置并启动网络服务"] },
  { type: "cards", section: "使用说明", audiences: "客户", title: "日常操作可归纳为四个工作台", intro: "不同工作台使用一致的状态、日志和刷新习惯。", cards: [
    ["设备信息", "确认 EID、eUICC 能力和证书状态。"], ["Profile 视图", "查看已安装 Profile 与状态；当前不执行下载/启停/删除。"],
    ["通知与策略", "投递通知、执行 Fallback、管理应急 Profile。"], ["连接与日志", "配置 EIM 协议、观察后台状态、停止服务、导出诊断。"] ] },
  { type: "table", section: "故障排查", audiences: "客户｜研发", title: "排障应按环境、设备、SDK、协议、GUI 五层逐级收敛", intro: "先确认最底层可用，再检查上层表现，避免把 GUI 错误直接归因于 eUICC。", columns: ["现象", "优先检查", "下一步"], rows: [
    ["WSL 无发行版", "以真实 Windows 用户执行 wsl --list --verbose", "确认 Ubuntu 已注册并显式指定发行版"],
    ["GUI 无法显示", "WSLg/DISPLAY、GTK 依赖", "用 SDK CLI 验证非 GUI 路径"],
    ["EID 查询失败", "串口、AT 驱动、权限、eUICC 响应", "开启 APDU/AT 日志"],
    ["网络服务失败", "URL/Broker、DNS、证书、端口", "分离 TLS 与协议握手问题"],
    ["退出卡住/崩溃", "后台线程和配置生命周期", "先停止服务再 deinit"] ] },
  { type: "table", section: "安全与生产化", audiences: "管理｜客户｜研发", title: "从开发工具走向生产部署，需要补强证书、权限、日志与升级机制", intro: "底层 HTTP 实现中存在证书验证待完善痕迹，生产使用必须完成安全审查。", columns: ["领域", "当前关注点", "生产要求"], rows: [
    ["TLS/DTLS", "证书路径和验证链需核验", "默认开启主机名与对端证书验证"],
    ["设备权限", "串口/PCSC 访问", "最小权限用户、udev 规则、审计"],
    ["敏感日志", "EID、Profile、证书、服务器信息", "脱敏、分级、轮转和访问控制"],
    ["配置密钥", "用户名密码/证书路径", "不明文入库，使用安全存储"],
    ["升级回滚", "脚本式部署", "版本化产物、兼容性清单、可回退包"] ] },
  { type: "section", section: "状态与路线图", audiences: "管理｜客户｜研发", title: "第四部分｜成熟度、风险与演进路线", subtitle: "把真实能力、接入缺口与后续设计建议放在同一张地图上" },
  { type: "cards", section: "成熟度", audiences: "管理｜客户｜研发", title: "当前最成熟的是只读查询与基础控制，最薄弱的是 Profile 生命周期闭环", intro: "成熟度来自代码路径核验，不代表所有硬件、eIM 或 SM-DP+ 环境均已完成系统验证。", cards: [
    ["可演示", "EID、eUICC 信息、证书、Profile 列表、EIM 配置、Fallback、应急、批量通知。"],
    ["需接线", "MQTT/LwM2M/HTTP 参数、单条通知、配置文件实际应用、状态回调展示。"],
    ["未完成", "Profile 下载、启用、禁用、删除 Wrapper 当前返回 eNotImpl。"],
    ["需加固", "线程生命周期、初始化状态、内存释放、证书验证和类型安全分发。"] ] },
  { type: "table", section: "文档一致性", audiences: "管理｜研发", title: "发布说明与当前代码存在差异，交付口径应以代码为准", intro: "例如 v1.1.0 将 Profile 管理列为完成，但 README、开发总结和 Wrapper 实现表明仍为占位。", columns: ["主题", "历史表述", "当前代码事实", "对外口径"], rows: [
    ["Profile 管理", "发布说明标记完成", "Wrapper 返回 eNotImpl", "未交付"],
    ["网络协议", "发布说明标记连接完成", "底层/Wrapper 存在，GUI 参数链不完整", "集成中"],
    ["配置体系", "文档描述较完整", "解析存在，应用链仍有缺口", "基础可用"],
    ["兼容性", "Linux/协议能力描述广泛", "AT + Ubuntu 为主验证路径", "按验证矩阵声明"] ] },
  { type: "timeline", section: "路线图", audiences: "管理｜客户｜研发", title: "建议用三个阶段把“可运行”推进到“可交付、可运维”", milestones: [
    ["阶段 1｜闭环", "补齐 Profile 管理、单条通知、网络参数和配置应用；建立真实初始化状态。"],
    ["阶段 2｜加固", "治理线程/内存、错误模型、证书验证、日志脱敏和自动化测试。"],
    ["阶段 3｜平台化", "命令注册表、daemon/worker、远程管理、可观测性与多驱动扩展。"] ] },
  { type: "table", section: "裁剪指南", audiences: "管理｜客户｜研发", title: "同一母版可按受众保留不同深度", intro: "页脚受众标签用于快速筛选；附录默认只在研发评审中保留。", columns: ["版本", "建议保留", "建议隐藏"], rows: [
    ["管理层版", "执行摘要、产品全景、成熟度、风险、路线图", "接口签名、构建细节、完整附录"],
    ["客户版", "能力、场景、兼容性、部署、使用、边界、安全", "内部代码风险与底层 API 索引"],
    ["研发版", "全稿，重点 SDK、Manager、部署与附录", "可仅隐藏管理层重复摘要"],
    ["售前短版", "封面、摘要、全景、能力地图、兼容性、部署、总结", "实现细节和风险页"] ] },
  { type: "section", section: "附录", audiences: "研发", title: "技术附录｜接口、配置、构建与术语", subtitle: "用于研发交接、技术评审和问题定位" },
  { type: "table", section: "API 附录", audiences: "研发", title: "公开 SDK API 索引｜生命周期与查询", intro: "签名以头文件为准；表中强调调用目的和释放责任。", columns: ["API", "作用", "资源/注意事项"], rows: [
    ["ipa_init_library", "初始化 SDK", "传入配置和事件回调"], ["ipa_deinit_library", "释放 SDK", "先停止后台服务"],
    ["ipa_register_task_callbacks", "注册任务创建/结束回调", "可传默认实现"], ["ipa__get_eid_cstring", "读取 EID", "调用方提供缓冲区"],
    ["ipa__get_euicc_info_1/2", "读取能力信息", "使用对应 free API"], ["ipa__get_certs", "读取证书/PKID", "使用 ipa__free_certs_data"],
    ["ipa__get_all_profiles_info", "读取 Profile 数组", "明确数组与 raw TLV 所有权"], ["ipa__get_eim_configuration", "读取 EIM 配置", "处理响应 TLV"] ] },
  { type: "table", section: "API 附录", audiences: "研发", title: "公开 SDK API 索引｜控制、通知与本地命令", intro: "控制类接口应增加确认、状态刷新和错误上下文。", columns: ["API 组", "代表入口", "说明"], rows: [
    ["Fallback", "ipa__execute_fallback_mechanism / ipa__return_from_fallback", "切换与返回"],
    ["Rollback", "ipa__execute_profile_rollback_result", "上报回滚结果"],
    ["Emergency", "ipa__enable_emergency_profile / disable", "应急 Profile 控制"],
    ["Notifications", "all / seq_number_single / remove / remove_all", "投递与清理"],
    ["Local commands", "set_default_dp_address / add_initial_eim", "本地配置"],
    ["Memory reset", "ipa_local__euicc_memory_reset", "高风险动作"],
    ["Immediate enabling", "configure_immediate_profile_enabling", "受 SGP.32 特性控制"] ] },
  { type: "table", section: "Wrapper 附录", audiences: "研发", title: "Manager Wrapper API 索引｜对上层隐藏 SDK 细节", intro: "Wrapper 应成为唯一的 GUI 到 SDK 边界，并承担资源、线程和错误语义统一。", columns: ["类别", "代表接口", "当前状态"], rows: [
    ["生命周期", "ipad_wrapper_init/deinit/is_initialized/get_version", "已实现，状态机需加固"],
    ["查询", "get_eid/get_euicc_info/get_profiles/get_certs/get_eim", "已实现并接入"],
    ["策略", "fallback/return/emergency", "已实现并接入"],
    ["通知", "all/single/remove/remove_all", "批量已接入，单条待接线"],
    ["协议", "connect_mqtt/lwm2m/http/stop", "封装存在，参数链待完善"],
    ["Profile 生命周期", "download/enable/disable/delete", "占位，返回 eNotImpl"] ] },
  { type: "table", section: "配置附录", audiences: "研发", title: "配置项应按设备、日志、协议和安全四个域管理", intro: "示例 JSON 提供默认值；最终有效值必须在启动日志中可追踪但不泄露敏感信息。", columns: ["域", "关键项", "校验"], rows: [
    ["设备", "串口、波特率、驱动类型", "路径存在、权限、连通性"],
    ["日志", "级别、输出位置", "可写、轮转、脱敏"],
    ["MQTT", "Broker、端口、Client ID、认证、TLS", "URI、证书、重连"],
    ["LwM2M", "端点、服务器、Bootstrap、DTLS", "端口、身份、PSK/证书"],
    ["HTTP", "URL、超时、证书", "HTTPS、主机名、对端验证"],
    ["UI", "窗口与显示选项", "默认值与范围"] ] },
  { type: "table", section: "代码导航", audiences: "研发", title: "从入口到协议层的代码导航", intro: "遇到问题时按调用方向查找，比按目录盲搜更高效。", columns: ["问题", "首先查看", "继续下钻"], rows: [
    ["接口声明", "ipa_sdk_pc/include/ipa.h", "typedefs.h / es10_typedefs.h"],
    ["Wrapper 行为", "ipad_wrapper.h", "src/sdk_wrapper/ipad_wrapper.c"],
    ["GUI 分发", "src/gui/gui_main.c", "app_api_definitions.h"],
    ["配置", "config_manager.c/h", "config/ipad_config.example.json"],
    ["ES10/TLV", "profile-assistant-commons/core/gsma/interfaces/es10", "tlv generator/extractor"],
    ["网络/硬件", "profile-assistant-commons/hw/linux", "mqtt/http/lwm2m/AT 实现"] ] },
  { type: "cards", section: "术语", audiences: "管理｜客户｜研发", title: "核心术语速查", intro: "对外材料应统一术语，避免把 eIM、eSIPa、SM-DP+ 和 Manager 混称为同一组件。", cards: [
    ["eUICC", "可远程配置 Profile 的嵌入式 UICC。"], ["Profile", "运营商订阅及其凭据与策略集合。"],
    ["IPA / IPAd", "IoT Profile Assistant / 本项目桌面管理形态。"], ["eIM", "eSIM IoT Remote Manager。"],
    ["SM-DP+", "订阅准备与 Profile 下载服务。"], ["ES10", "IPA 与 eUICC 交互的接口族。"],
    ["APDU", "与安全元件通信的命令/响应单元。"], ["TLV", "Tag-Length-Value 编码结构。"] ] },
  { type: "closing", section: "总结", audiences: "管理｜客户｜研发", title: "把能力边界说清楚，是 IPAd 从工程样机走向可交付产品的第一步", subtitle: "当前仓库已经具备完整技术骨架；下一阶段应优先补齐 Profile 闭环、GUI 参数链、线程资源治理与生产安全。", note: "IPAd SDK & Manager · Architecture / Interfaces / Deployment" }
];

export const sourceSlideForType = {
  cover: 1,
  agenda: 2,
  section: 1,
  cards: 4,
  flow: 12,
  layers: 5,
  table: 9,
  timeline: 12,
  bullets: 7,
  closing: 14,
};
