#ifndef IPAD_ERRORS_H
#define IPAD_ERRORS_H

typedef enum {
    IPAD_OK = 0,
    IPAD_ERR_BAD_REQUEST = 1000,
    IPAD_ERR_INVALID_PARAMS = 1001,
    IPAD_ERR_METHOD_NOT_FOUND = 1002,
    IPAD_ERR_WORKER_UNAVAILABLE = 2000,
    IPAD_ERR_WORKER_CRASHED = 2001,
    IPAD_ERR_WORKER_TIMEOUT = 2002,
    IPAD_ERR_SDK_NOT_INITIALIZED = 3000,
    IPAD_ERR_SDK_FAILED = 3001,
    IPAD_ERR_DEVICE_UNAVAILABLE = 4000,
    IPAD_ERR_TASK_NOT_FOUND = 5000,
    IPAD_ERR_INTERNAL = 9000
} ipad_error_t;

const char *ipad_error_to_string(ipad_error_t error);

#endif
